# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - windows
  - osx

julia:
  # - 1.0
  - 1.2
  - 1.5

notifications:
  email: false

addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib

script:
  - julia test/deps.jl
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: osx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    pkg"add https://github.com/JuliaPOMDP/RLInterface.jl";
                                    pkg"add https://github.com/sisl/POMDPStressTesting.jl";
                                    Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
